---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - patch
  - watch
- apiGroups:
  - flipper.io
  resources:
  - flippers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - flipper.io
  resources:
  - flippers/finalizers
  verbs:
  - update
- apiGroups:
  - flipper.io
  resources:
  - flippers/status
  verbs:
  - get
  - patch
  - update
